language: node_js

node_js:
 - "8"
 - "10"
 # FIXME: something is precluding perseo-fe to work in Node v12. Some tests are failing
 #- "12"

branches:
  only:
    #- master
    - fiqare-improvements-1

services:
 - mongodb

addons:
  apt:
    sources:
    - mongodb-3.6-precise
    packages:
    - mongodb-org-server

install:
 # It seems to be a good idea to clean before install
 # see https://travis-ci.community/t/i-needed-an-explicit-cleanup-before-starting-my-tests-to-have-then-working-again-is-that-normal/5512/2
 - npm run clean
 - npm install

before_install:
 - npm update -q

before_script:
 - npm run lint
# - npm run lint:text
 - npm run lint:md

after_script: 
  - npm run test:coveralls

